const actionTypes = {
  INITIALIZE_DATA: 'INITIALIZE_DATA',
  SELECT_PHOTOGRAPHER: 'SELECT_PHOTOGRAPHER',
  SELECT_COUNTY: 'SELECT_COUNTY',
  SELECT_PHOTO: 'SELECT_PHOTO',
  LOAD_SIDEBAR_PHOTOS: 'LOAD_SIDEBAR_PHOTOS',
  LOAD_COUNTIES: 'LOAD_COUNTIES',
  MAP_MOVED: 'MAP_MOVED',
  GENERATE_RANDOM_PHOTO_NUMBERS: 'GENERATE_RANDOM_PHOTO_NUMBERS',
  DIMENSIONS_CALCULATED: 'DIMENSIONS_CALCULATED',
}

export default actionTypes;
