const actionTypes = {
  INITIALIZE_DATA: 'INITIALIZE_DATA',
  SELECT_PHOTOGRAPHER: 'SELECT_PHOTOGRAPHER',
  CLEAR_PHOTOGRAPHER: 'CLEAR_PHOTOGRAPHER',
  SELECT_COUNTY: 'SELECT_COUNTY',
  SELECT_CITY: 'SELECT_CITY',
  SELECT_STATE: 'SELECT_STATE',
  SELECT_NATION: 'SELECT_NATION',
  SELECT_PHOTO: 'SELECT_PHOTO',
  SET_PHOTO_OFFSET: 'SET_PHOTO_OFFSET',
  SET_TIME_RANGE: 'SET_TIME_RANGE',
  LOAD_COUNTIES: 'LOAD_COUNTIES',
  LOAD_CITIES: 'LOAD_CITIES',
  LOAD_TIMELINE_CELLS: 'LOAD_TIMELINE_CELLS',
  MAP_MOVED: 'MAP_MOVED',
  GENERATE_RANDOM_PHOTO_NUMBERS: 'GENERATE_RANDOM_PHOTO_NUMBERS',
  DIMENSIONS_CALCULATED: 'DIMENSIONS_CALCULATED',
  CLOSE_WELCOME: 'CLOSE_WELCOME',
  SELECT_MAP_VIEW: 'SELECT_MAP_VIEW',
  SET_MAP_SCALE: 'SET_MAP_SCALE',
}

export default actionTypes;
