const actionTypes = {
  INITIALIZE_DATA: 'INITIALIZE_DATA',
  INITIALIZED: 'INITIALIZED',
  SET_STATE: 'SET_STATE',
  SET_PHOTO_OFFSET: 'SET_PHOTO_OFFSET',
  SET_TIME_RANGE: 'SET_TIME_RANGE',
  MAP_MOVED: 'MAP_MOVED',
  DIMENSIONS_CALCULATED: 'DIMENSIONS_CALCULATED',
  CLOSE_WELCOME: 'CLOSE_WELCOME',
  SET_MAP_SCALE: 'SET_MAP_SCALE',
  SET_FILTER_TERMS: 'SET_FILTER_TERMS',
  CLEAR_FILTER_TERMS: 'CLEAR_FILTER_TERMS',
  TOGGLE_EXPANDED_SIDEBAR: 'TOGGLE_EXPANDED_SIDEBAR',
  TOGGLE_LIGHTBOX: 'TOGGLE_LIGHTBOX',
  TOGGLE_SEARCH: 'TOGGLE_SEARCH',
  TOGGLE_VIZ: 'TOGGLE_VIZ',
};

export default actionTypes;
